# Experiment Configuration
experiment:
  name: "optimizer_comparison"
  seeds: [10]

# Data Configuration
data:
  n_samples: 300
  in_dims: [14]
  out_dims: [2]
  test_size: 0.2

# Global Training Configuration (for settings that apply to ALL runs)
training:
  num_epochs: 20
  shuffle: true
  use_tqdm: 
  time_budget: 50
  patience: 5


# Model Configuration
models:
  BinClass:
    model_seed: 100
    loss_function: "CrossEntropyLoss"
  LinReg:
    model_seed: 100
    loss_function: "MSELoss"

# Optimizer Configuration (with specific hyperparameters for each)
optimizers:
  FullAdaGrad:
    enabled: false
    requires_rank: false
    # --- FullAdaGrad-specific hyperparameters ---
    learning_rates: [1e-3, 1e-4, 1e-5]
    batch_size: [1, 32, 64]              # change for gradients
    eps: [1e-3, 1e-4, 1e-5, 1e-2, 0.1, 0.5]
  # --- Other optimizers would follow the same pattern ---

  AdaGramPS:
    enabled: true
    requires_rank: true
    testing: false
    # --- AdaGramPS-specific hyperparameters ---
    learning_rates: [1e-2, 1e-3, 1e-4, 1e-5]
    batch_size: [1, 32, 64]
    eps: [1e-3, 1e-4, 1e-5, 1e-2, 0.1, 0.5]
    ranks: [1, 2, 3, 4, 5, null]
    alphas: [1, 0, 0.2, 0.5, 0.8]

  Shampoo:
    enabled: true
    requires_rank: false
    learning_rates: [1e-2, 1e-3, 1e-4, 1e-5]
    eps: [1e-3, 1e-4, 1e-5, 1e-2, 0.1, 0.5]
    batch_size: [1, 32, 64]

  KATE:
    enabled: true
    requires_rank: false
    # --- KATE-specific hyperparameters would go here ---
    learning_rates: [1e-2, 1e-3, 1e-4, 1e-5]
    batch_size: [1, 32, 64]
    eps: [1e-3, 1e-4, 1e-5, 1e-2, 0.1, 0.5]


  Torch_Adagrad:
    enabled: true
    requires_rank: false
    # --- Torch Adagrad-specific hyperparameters ---
    learning_rates: [1e-2, 1e-3, 1e-4, 1e-5]                                                               # Adagrad often works well with higher LRs
    batch_size: [1, 32, 64]
    eps: [1e-3, 1e-4, 1e-5, 1e-2, 0.1, 0.5]

  Vanilla_SGD:
    enabled: true
    requires_rank: false
    # --- SGD-specific hyperparameters (note: no 'eps' or 'ranks') ---
    learning_rates: [1e-2, 1e-3, 1e-4, 1e-5]    
    batch_size: [1, 32, 64]
    eps: [nan]

  AdaGramFR_svd:
    enabled: true
    requires_rank: true
    testing: false
    # --- AdaGramPS-specific hyperparameters ---
    learning_rates: [1e-2, 1e-3, 1e-4, 1e-5, 1e-2]
    batch_size: [1, 32, 64]
    eps: [1e-3, 1e-4, 1e-5, 1e-2, 0.1, 0.5]
    ranks: [1, 2, 3, 4, 5, null]

# Output Configuration
output:
  results_dir: "results"
  plots_dir: "plots"
  gradients_dir: "gradients"

# Tasks Configuration
tasks:
  enabled_tasks: ["BinClass"] # Options: ["BinClass", "LinReg"]

# Dataset Configuration
dataset:
  type: "CorrelatedAnisotropicDataset" # Options: SparseDataset, CorrelatedDataset, LinearDataset, MNIST, AU, Heart
  sparse_config:
    if_class: true
  correlated_config:
    correlation: 0.8
  linear_config:
    noise_std: 0.1