import os
import pandas
import argparse

from ExperimentRunner import ExperimentRunner
from src.utils.Config import Config

def main(config_path, mode, output_filename):
    """Main function to run the experiment."""
    
    print(f"Loading configuration from: {config_path}")
    config = Config(config_path)
    
    print("Initializing ExperimentRunner...")
    runner = ExperimentRunner(config, mode)
    
    print("Running experiment...")
    runner.run_experiment()
    print("Experiment finished.")

    if not hasattr(runner, 'results') or not runner.results:
        print("Warning: No results were generated by the experiment.")
        return
        
    df = pandas.DataFrame(runner.results)

    results_dir = config.get("output.results_dir")
    if results_dir:
        os.makedirs(results_dir, exist_ok=True)

        filepath = os.path.join(results_dir, output_filename)
        
        print(f"Saving results to: {filepath}")
        df.to_csv(filepath, index=False)
        print("Results saved successfully.")
    else:
        raise ValueError("'output.results_dir' not found in the configuration file.")

if __name__ == "__main__":
    # --- Command-Line Argument Parsing ---
    parser = argparse.ArgumentParser(
        description="Run an experiment using a specified configuration file."
    )

    # Argument for the config file path.
    parser.add_argument(
        "--config",
        type=str,
        default="./configs/classification/config_Synth_Corr_Aniso.yaml",
        help="Path to the YAML configuration file for the experiment."
    )

    parser.add_argument(
        "--mode",
        type=str,
        default="epochs",
        help="Mode for an experiment"
    )

    # Argument for the output filename.
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        help="Filename for the output CSV file (e.g., 'results.csv')."
    )

    args = parser.parse_args()

    main(config_path=args.config, mode=args.mode, output_filename=args.output)
